#include <iostream>

char str[64] = { "\0" };
int idToNationName(int Area_ID) {
    switch (Area_ID) {
        case 4:  strcpy_s(str,sizeof(str)/sizeof(str[0]),"Afghanistan");  break;
        case 8:  strcpy_s(str,sizeof(str)/sizeof(str[0]),"Albania");  break;
        case 10: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Antarctica");  break;
        case 12: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Algeria");  break;
        case 16: strcpy_s(str,sizeof(str)/sizeof(str[0]),"American Samoa");  break;
        case 20: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Andorra");  break;
        case 24: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Angola");  break;
        case 28: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Antigua and Barbuda");  break;
        case 31: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Azerbaijan");  break;
        case 32: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Argentina");  break;
        case 36: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Australia");  break;
        case 40: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Austria");  break;
        case 44: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Bahamas (the)");  break;
        case 48: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Bahrain");  break;
        case 50: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Bangladesh");  break;
        case 51: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Armenia");  break;
        case 52: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Barbados");  break;
        case 56: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Belgium");  break;
        case 60: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Bermuda");  break;
        case 64: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Bhutan");  break;
        case 68: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Bolivia (Plurinational State of)");  break;
        case 70: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Bosnia and Herzegovina");  break;
        case 72: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Botswana");  break;
        case 74: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Bouvet Island");  break;
        case 76: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Brazil");  break;
        case 84: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Belize");  break;
        case 86: strcpy_s(str,sizeof(str)/sizeof(str[0]),"British Indian Ocean Territory (the)");  break;
        case 90: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Solomon Islands");  break;
        case 92: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Virgin Islands (British)");  break;
        case 96: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Brunei Darussalam");  break;
        case 100: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Bulgaria");  break;
        case 104: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Myanmar");  break;
        case 108: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Burundi");  break;
        case 112: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Belarus");  break;
        case 116: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Cambodia");  break;
        case 120: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Cameroon");  break;
        case 124: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Canada");  break;
        case 132: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Cabo Verde");  break;
        case 136: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Cayman Islands (the)");  break;
        case 140: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Central African Republic (the)");  break;
        case 144: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Sri Lanka");  break;
        case 148: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Chad");  break;
        case 152: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Chile");  break;
        case 156: strcpy_s(str,sizeof(str)/sizeof(str[0]),"China");  break;
        case 158: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Taiwan (Province of China)");  break;
        case 162: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Christmas Island");  break;
        case 166: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Cocos (Keeling) Islands (the)");  break;
        case 170: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Colombia");  break;
        case 174: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Comoros (the)");  break;
        case 175: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Mayotte");  break;
        case 178: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Congo (the)");  break;
        case 180: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Congo (the Democratic Republic of the)");  break;
        case 184: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Cook Islands (the)");  break;
        case 188: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Costa Rica");  break;
        case 191: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Croatia");  break;
        case 192: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Cuba");  break;
        case 196: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Cyprus");  break;
        case 203: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Czechia");  break;
        case 204: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Benin");  break;
        case 208: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Denmark");  break;
        case 212: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Dominica");  break;
        case 214: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Dominican Republic (the)");  break;
        case 218: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Ecuador");  break;
        case 222: strcpy_s(str,sizeof(str)/sizeof(str[0]),"El Salvador");  break;
        case 226: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Equatorial Guinea");  break;
        case 231: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Ethiopia");  break;
        case 232: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Eritrea");  break;
        case 233: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Estonia");  break;
        case 234: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Faroe Islands (the)");  break;
        case 238: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Falkland Islands (the) [Malvinas]");  break;
        case 239: strcpy_s(str,sizeof(str)/sizeof(str[0]),"South Georgia and the South Sandwich Islands");  break;
        case 242: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Fiji");  break;
        case 246: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Finland");  break;
        case 248: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Åland Islands");  break;
        case 250: strcpy_s(str,sizeof(str)/sizeof(str[0]),"France");  break;
        case 254: strcpy_s(str,sizeof(str)/sizeof(str[0]),"French Guiana");  break;
        case 258: strcpy_s(str,sizeof(str)/sizeof(str[0]),"French Polynesia");  break;
        case 260: strcpy_s(str,sizeof(str)/sizeof(str[0]),"French Southern Territories (the)");  break;
        case 262: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Djibouti");  break;
        case 266: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Gabon");  break;
        case 268: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Georgia");  break;
        case 270: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Gambia (the)");  break;
        case 275: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Palestine, State of");  break;
        case 276: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Germany");  break;
        case 288: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Ghana");  break;
        case 292: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Gibraltar");  break;
        case 296: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Kiribati");  break;
        case 300: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Greece");  break;
        case 304: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Greenland");  break;
        case 308: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Grenada");  break;
        case 312: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Guadeloupe");  break;
        case 316: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Guam");  break;
        case 320: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Guatemala");  break;
        case 324: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Guinea");  break;
        case 328: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Guyana");  break;
        case 332: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Haiti");  break;
        case 334: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Heard Island and McDonald Islands");  break;
        case 336: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Holy See (the)");  break;
        case 340: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Honduras");  break;
        case 344: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Hong Kong");  break;
        case 348: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Hungary");  break;
        case 352: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Iceland");  break;
        case 356: strcpy_s(str,sizeof(str)/sizeof(str[0]),"India");  break;
        case 360: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Indonesia");  break;
        case 364: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Iran (Islamic Republic of)");  break;
        case 368: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Iraq");  break;
        case 372: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Ireland");  break;
        case 376: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Israel");  break;
        case 380: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Italy");  break;
        case 384: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Côte d'Ivoire");  break;
        case 388: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Jamaica");  break;
        case 392: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Japan");  break;
        case 398: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Kazakhstan");  break;
        case 400: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Jordan");  break;
        case 404: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Kenya");  break;
        case 408: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Korea (the Democratic People's Republic of)");  break;
        case 410: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Korea (the Republic of)");  break;
        case 414: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Kuwait");  break;
        case 417: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Kyrgyzstan");  break;
        case 418: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Lao People's Democratic Republic (the)");  break;
        case 422: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Lebanon");  break;
        case 426: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Lesotho");  break;
        case 428: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Latvia");  break;
        case 430: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Liberia");  break;
        case 434: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Libya");  break;
        case 438: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Liechtenstein");  break;
        case 440: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Lithuania");  break;
        case 442: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Luxembourg");  break;
        case 446: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Macao");  break;
        case 450: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Madagascar");  break;
        case 454: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Malawi");  break;
        case 458: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Malaysia");  break;
        case 462: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Maldives");  break;
        case 466: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Mali");  break;
        case 470: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Malta");  break;
        case 474: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Martinique");  break;
        case 478: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Mauritania");  break;
        case 480: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Mauritius");  break;
        case 484: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Mexico");  break;
        case 492: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Monaco");  break;
        case 496: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Mongolia");  break;
        case 498: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Moldova (the Republic of)");  break;
        case 499: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Montenegro");  break;
        case 500: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Montserrat");  break;
        case 504: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Morocco");  break;
        case 508: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Mozambique");  break;
        case 512: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Oman");  break;
        case 516: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Namibia");  break;
        case 520: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Nauru");  break;
        case 524: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Nepal");  break;
        case 528: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Netherlands (the)");  break;
        case 531: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Curaçao");  break;
        case 533: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Aruba");  break;
        case 534: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Sint Maarten (Dutch part)");  break;
        case 535: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Bonaire, Sint Eustatius and Saba");  break;
        case 540: strcpy_s(str,sizeof(str)/sizeof(str[0]),"New Caledonia");  break;
        case 548: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Vanuatu");  break;
        case 554: strcpy_s(str,sizeof(str)/sizeof(str[0]),"New Zealand");  break;
        case 558: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Nicaragua");  break;
        case 562: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Niger (the)");  break;
        case 566: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Nigeria");  break;
        case 570: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Niue");  break;
        case 574: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Norfolk Island");  break;
        case 578: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Norway");  break;
        case 580: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Northern Mariana Islands (the)");  break;
        case 581: strcpy_s(str,sizeof(str)/sizeof(str[0]),"United States Minor Outlying Islands (the)");  break;
        case 583: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Micronesia (Federated States of)");  break;
        case 584: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Marshall Islands (the)");  break;
        case 585: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Palau");  break;
        case 586: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Pakistan");  break;
        case 591: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Panama");  break;
        case 598: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Papua New Guinea");  break;
        case 600: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Paraguay");  break;
        case 604: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Peru");  break;
        case 608: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Philippines (the)");  break;
        case 612: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Pitcairn");  break;
        case 616: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Poland");  break;
        case 620: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Portugal");  break;
        case 624: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Guinea-Bissau");  break;
        case 626: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Timor-Leste");  break;
        case 630: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Puerto Rico");  break;
        case 634: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Qatar");  break;
        case 638: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Réunion");  break;
        case 642: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Romania");  break;
        case 643: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Russian Federation (the)");  break;
        case 646: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Rwanda");  break;
        case 652: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Saint Barthélemy");  break;
        case 654: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Saint Helena, Ascension and Tristan da Cunha");  break;
        case 659: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Saint Kitts and Nevis");  break;
        case 660: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Anguilla");  break;
        case 662: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Saint Lucia");  break;
        case 663: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Saint Martin (French part)");  break;
        case 666: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Saint Pierre and Miquelon");  break;
        case 670: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Saint Vincent and the Grenadines");  break;
        case 674: strcpy_s(str,sizeof(str)/sizeof(str[0]),"San Marino");  break;
        case 678: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Sao Tome and Principe");  break;
        case 682: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Saudi Arabia");  break;
        case 686: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Senegal");  break;
        case 688: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Serbia");  break;
        case 690: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Seychelles");  break;
        case 694: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Sierra Leone");  break;
        case 702: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Singapore");  break;
        case 703: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Slovakia");  break;
        case 704: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Viet Nam");  break;
        case 705: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Slovenia");  break;
        case 706: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Somalia");  break;
        case 710: strcpy_s(str,sizeof(str)/sizeof(str[0]),"South Africa");  break;
        case 716: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Zimbabwe");  break;
        case 724: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Spain");  break;
        case 728: strcpy_s(str,sizeof(str)/sizeof(str[0]),"South Sudan");  break;
        case 729: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Sudan (the)");  break;
        case 732: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Western Sahara*");  break;
        case 740: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Suriname");  break;
        case 744: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Svalbard and Jan Mayen");  break;
        case 748: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Eswatini");  break;
        case 752: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Sweden");  break;
        case 756: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Switzerland");  break;
        case 760: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Syrian Arab Republic (the)");  break;
        case 762: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Tajikistan");  break;
        case 764: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Thailand");  break;
        case 768: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Togo");  break;
        case 772: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Tokelau");  break;
        case 776: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Tonga");  break;
        case 780: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Trinidad and Tobago");  break;
        case 784: strcpy_s(str,sizeof(str)/sizeof(str[0]),"United Arab Emirates (the)");  break;
        case 788: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Tunisia");  break;
        case 792: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Turkey");  break;
        case 795: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Turkmenistan");  break;
        case 796: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Turks and Caicos Islands (the)");  break;
        case 798: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Tuvalu");  break;
        case 800: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Uganda");  break;
        case 804: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Ukraine");  break;
        case 807: strcpy_s(str,sizeof(str)/sizeof(str[0]),"North Macedonia");  break;
        case 818: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Egypt");  break;
        case 826: strcpy_s(str,sizeof(str)/sizeof(str[0]),"United Kingdom of Great Britain and Northern Ireland (the)");  break;
        case 831: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Guernsey");  break;
        case 832: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Jersey");  break;
        case 833: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Isle of Man");  break;
        case 834: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Tanzania, the United Republic of");  break;
        case 840: strcpy_s(str,sizeof(str)/sizeof(str[0]),"United States of America (the)");  break;
        case 850: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Virgin Islands (U.S.)");  break;
        case 854: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Burkina Faso");  break;
        case 858: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Uruguay");  break;
        case 860: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Uzbekistan");  break;
        case 862: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Venezuela (Bolivarian Republic of)");  break;
        case 876: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Wallis and Futuna");  break;
        case 882: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Samoa");  break;
        case 887: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Yemen");  break;
        case 894: strcpy_s(str,sizeof(str)/sizeof(str[0]),"Zambia");  break;
        default: return 0;
    }
    return 1;
}
void printNation(int ID) {
    if (idToNationName(ID)) {
        printf("%s\n", str);
    }
    return;
}

int main()
{
    if (idToNationName(4)) {
        printf("%s\n",str);
    }

    printNation(156);
}
